### ISSUE TITLE
Incorrect `ElementHandle.boundingBox` result `x` and `y` when element has padding

### ISSUE THREAD

**Issue by jaydenseric** [lino-levan/astral#136]
If you have an element styled so that its bounding box is at viewport coordinates `x` 0 and `y` 0:

```css
#target {
  position: fixed;
  left: 0;
  top: 0;
  padding: 20px;
}
```

The `ElementHandle.boundingBox` result `x` and `y` incorrectly becomes the padding value, in this case 20, when they should be 0.

This is wreaking havoc with attempts to use `ElementHandle.screenshot`, as the screenshots are shifted off the target element bounding box by the same amount as the element's padding.
